FROM mup-tests-server
RUN yum -y update
RUN yum -y install lxc iptables && \
    curl https://get.docker.com/ | sh && usermod -aG docker $(whoami)
RUN echo 'DOCKER_OPTS="--storage-driver=vfs"' >> /etc/default/docker
